version: '3.8'
services:
  server:
    build:
      context: ./postgres-server
    ports:
      - "5433:5433"
    environment:
      DATABASE_URL: "postgresql://postgres:040697@db:5432/whisper"
      PORT: 5433
    restart: on-failure
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "040697"
      POSTGRES_DB: whisper
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  front:
    build:
      context: ./whisper-front
      args:
        REACT_APP_API_URL: http://server:5433
    ports:
      - "3000:80"
      
  twitter-bot-service:
    build: 
      context: ./Tweeter-Bot
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - SERVER_PORT=5433
    volumes:
      - ./Tweeter-Bot:/app
    restart: always

  comment-generator-service:
    build: 
      context: ./Comment-Generator
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./Comment-Generator:/app
    restart: always 

volumes:
  postgres_data: